### ISSUE TITLE
Getting final representation 

### ISSUE THREAD

**Issue by omidb** [stanfordnlp/spinn#5]
Hi,

Most script I found are for re-producing the paper's output. Would you please explain how can I use it to calculate the final representation for given sentence?

Thanks

**Comment by hans** [comment]
You're right — the scripts are tailored to this particular pipeline. But you can certainly dig in and change what we are doing with the data.

Check out [`fat_classifier.py`][1] to see how we compute representations of two sentences for the SNLI task (called `premise_vector` and `hypothesis_vector` in the code that I linked to). You could delete everything after this point and compile a Theano function which just outputs the representations, if that's what you're interested in.

[1]: https://github.com/stanfordnlp/spinn/blob/master/python/spinn/models/fat_classifier.py#L227
