### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '../glove/glove.840B.300d.txt'

### ISSUE THREAD

**Issue by ch3njust1n** [stanfordnlp/spinn#6]
Loading ../snli_1.0/snli_1.0_train.jsonl
Loading ../snli_1.0/snli_1.0_dev.jsonl
[1] In open vocabulary mode. Using loaded embeddings without fine-tuning.
[1] Constructing vocabulary...
[1] Found 36675 word types.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jsc0606/Desktop/muse/spinn/python/spinn/models/fat_classifier.py", line 823, in <module>
    run(only_forward=FLAGS.expanded_eval_only_mode)
  File "/home/jsc0606/Desktop/muse/spinn/python/spinn/models/fat_classifier.py", line 513, in run
    sentence_pair_data=data_manager.SENTENCE_PAIR_DATA)
  File "/home/jsc0606/Desktop/muse/spinn/python/spinn/util/data.py", line 230, in BuildVocabulary
    embedding_path, types_in_data, CORE_VOCABULARY)
  File "/home/jsc0606/Desktop/muse/spinn/python/spinn/util/data.py", line 245, in BuildVocabularyForASCIIEmbeddingFile
    with open(path, 'r') as f:
IOError: [Errno 2] No such file or directory: '../glove/glove.840B.300d.txt'

**Comment by ch3njust1n** [comment]
When I run the command ./checkpoints/spinn.sh, it asks if it should download the file, but later on crashes with the error above.

**Comment by hans** [comment]
Hi Justin, I can't reproduce your crash. What does the `checkpoints/spinn.sh` script output at the very start when you're prompted to download embeddings? Maybe there was an error with `wget` / `tar`?
(What platform are you running this on?)

**Comment by ch3njust1n** [comment]
I'm running this on Ubuntu 16.04 behind a proxy.

Could not find GloVe embeddings at ../glove/glove.840B.300d.txt.
Should we download them? (~2G download) (y/n) y
--2016-07-13 13:27:16--  http://nlp.stanford.edu/data/glove.840B.300d.zip
Proxy request sent, awaiting response... 200 OK
Length: 2176768927 (2.0G) [application/zip]
Saving to: ‘glove.zip’

glove.zip                                            100%[======================================================================================================================>]   2.03G  11.6MB/s    in 2m 55s  

2016-07-13 13:30:12 (11.8 MB/s) - ‘glove.zip’ saved [2176768927/2176768927]

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains ‘l\331,L\336w\302kmԅN’ where numeric off_t value expected
tar: Archive contains ‘\017\201eCn\177'X\365\2243%’ where numeric off_t value expected
tar: Exiting with failure status due to previous errors
Failed to extract GloVe embeddings.
THEANO_FLAGS: allow_gc=False,cuda.root=/usr/bin/cuda,warn_float64=warn,device=gpu,floatX=float32,
Running command:
python -m spinn.models.fat_classifier --data_type snli --embedding_data_path ../glove/glove.840B.300d.txt --log_path ../logs --training_data_path ../snli_1.0/snli_1.0_train.jsonl --experiment_name spinn --eval_data_path ../snli_1.0/snli_1.0_dev.jsonl --ckpt_path spinn.ckpt_best   --batch_size 32 --connect_tracking_comp --embedding_keep_rate 0.938514416034 --eval_seq_length 50 --init_range 0.005 --l2_lambda 2.76018187539e-05 --learning_rate 0.00103428201391 --model_dim 600 --model_type Model1 --num_sentence_pair_combination_layers 1 --semantic_classifier_keep_rate 0.949455648614 --seq_length 50 --tracking_lstm_hidden_dim 44 --transition_cost_scale 0.605159568546 --use_tracking_lstm  --word_embedding_dim 300 --predict_use_cell
ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.
[1] Flag values:
{   '?': None,
    'allow_gt_transitions_in_eval': False,
    'batch_size': 32,
    'ckpt_interval_steps': 5000,
    'ckpt_on_best_dev_error': True,
    'ckpt_path': 'spinn.ckpt_best',
    'classifier_type': 'MLP',
    'clipping_max_value': 5.0,
    'connect_tracking_comp': True,
    'context_sensitive_shift': False,
    'context_sensitive_use_relu': False,
    'data_type': 'snli',
    'embedding_data_path': '../glove/glove.840B.300d.txt',
    'embedding_keep_rate': 0.938514416034,
    'eval_data_path': '../snli_1.0/snli_1.0_dev.jsonl',
    'eval_interval_steps': 100,
    'eval_output_paths': None,
    'eval_seq_length': 50,
    'expanded_eval_only_mode': False,
    'experiment_name': 'spinn',
    'help': None,
    'helpshort': None,
    'helpxml': None,
    'init_range': 0.005,
    'initialize_hyp_tracking_state': False,
    'l2_lambda': 2.76018187539e-05,
    'learning_rate': 0.00103428201391,
    'learning_rate_decay_per_10k_steps': 0.75,
    'log_path': '../logs',
    'lstm_composition': True,
    'model_dim': 600,
    'model_type': 'Model1',
    'num_sentence_pair_combination_layers': 1,
    'predict_use_cell': True,
    'resnet_unit_depth': 2,
    'scheduled_sampling_exponent_base': 0.99,
    'semantic_classifier_keep_rate': 0.949455648614,
    'sentence_pair_combination_layer_dim': 1024,
    'seq_length': 50,
    'skip_saved_unsavables': False,
    'statistics_interval_steps': 100,
    'tracking_lstm_hidden_dim': 44,
    'training_data_path': '../snli_1.0/snli_1.0_train.jsonl',
    'training_steps': 500000,
    'transition_cost_scale': 0.605159568546,
    'use_attention': 'None',
    'use_difference_feature': True,
    'use_product_feature': True,
    'use_tracking_lstm': True,
    'word_embedding_dim': 300,
    'write_predicted_label': False}
Loading ../snli_1.0/snli_1.0_train.jsonl
Loading ../snli_1.0/snli_1.0_dev.jsonl
[1] In open vocabulary mode. Using loaded embeddings without fine-tuning.
[1] Constructing vocabulary...
[1] Found 36675 word types.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/spinn/python/spinn/models/fat_classifier.py", line 823, in <module>
    run(only_forward=FLAGS.expanded_eval_only_mode)
  File "/spinn/python/spinn/models/fat_classifier.py", line 513, in run
    sentence_pair_data=data_manager.SENTENCE_PAIR_DATA)
  File "/spinn/python/spinn/util/data.py", line 230, in BuildVocabulary
    embedding_path, types_in_data, CORE_VOCABULARY)
  File "/spinn/python/spinn/util/data.py", line 245, in BuildVocabularyForASCIIEmbeddingFile
    with open(path, 'r') as f:
IOError: [Errno 2] No such file or directory: '../glove/glove.840B.300d.txt'

**Comment by ch3njust1n** [comment]
This is an issue with my proxy. I ended up just manually downloading the zip, made the glove directory in the spinn directory, and placed the text file in that folder. Thanks for the help anyways. Closing this issue now.
